Feature ETP-794: Add unit tests
etendosoftware/com.etendoerp.etendorx pull request #6
Opened 2024-12-05 19:06 UTC by Emi-Polliotti

2024-12-09 17:00 UTC, ivanrobledofutit commented on src-test/src/com/etendoerp/etendorx/GetTokenURLTest.java
> +            mockedAuthUtils.when(() -> RXConfigUtils.getRXConfig("auth")).thenReturn(rxConfig);
Podrías agregar una constante para "auth" ya que se repite 4 veces en diferentes partes.
Se que tenes un AUTH, pero es para hacer referencia a "/auth".

2024-12-09 17:08 UTC, ivanrobledofutit commented on src-test/src/com/etendoerp/etendorx/BuildConfigTest.java
> +        source.put("key", "value");
Usar la constante de VALUE que creaste y revisar de usar en otros lados que se menciona.

2024-12-10 18:00 UTC, fran-roig approved these changes

2024-12-10 18:05 UTC, ivanrobledofutit approved these changes

2024-12-10 19:36 UTC, valeg-etendo requested changes

2024-12-10 19:36 UTC, valeg-etendo commented on src-test/src/com/etendoerp/etendorx/datasource/EntityFieldSelectedFiltersTest.java
> +        "getSelectedIds", "getModuleIds", "getJavaMappingIds",
`getJavaMappingIds`
I recommend passing to utils as they are used several times

2024-12-10 19:36 UTC, valeg-etendo commented on src-test/src/com/etendoerp/etendorx/datasource/ManageEntityFieldsDSJavaMappingTest.java
> +        when(query.setParameter(eq("etrxProjectionEntityId"), any())).thenReturn(query);
`etrxProjectionEntityId `
I recommend passing to utils as they are used several times

2024-12-10 19:36 UTC, valeg-etendo commented on src-test/src/com/etendoerp/etendorx/datasource/ManageEntityFieldsDSProjectionEntityTest.java
> +        when(query.setParameter(eq("etrxProjectionEntityId"), any())).thenReturn(query);
`etrxProjectionEntityId `
I recommend passing to utils as they are used several times

2024-12-10 19:36 UTC, valeg-etendo commented on src-test/src/com/etendoerp/etendorx/events/CheckEntityInEntityMappingEventHandlerTest.java
> +              eq("ETRX_WrongEntityName"),
`ETRX_WrongEntityName `
I recommend passing to utils as they are used several times

2024-12-10 19:36 UTC, valeg-etendo commented on src-test/src/com/etendoerp/etendorx/selector/ETRXSelectorFieldPropertyDataSourceTest.java
> +    when(referencedProperty.getColumnName()).thenReturn("AD_Image_ID");
`AD_Image_ID `
I recommend passing to utils as they are used several times

2024-12-11 15:51 UTC, valeg-etendo approved these changes

2024-12-11 15:55 UTC, merged